// Code generated by "stringer -type=Action"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionNull-0]
	_ = x[ActionBuy-1]
	_ = x[ActionSell-2]
}

const _Action_name = "ActionNullActionBuyActionSell"

var _Action_index = [...]uint8{0, 10, 19, 29}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
