// Code generated by mockery v2.20.0. DO NOT EDIT.

package mock

import (
	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// Trader is an autogenerated mock type for the Trader type
type Trader struct {
	mock.Mock
}

// Buy provides a mock function with given fields: amount
func (_m *Trader) Buy(amount decimal.Decimal) error {
	ret := _m.Called(amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(decimal.Decimal) error); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sell provides a mock function with given fields: amount
func (_m *Trader) Sell(amount decimal.Decimal) error {
	ret := _m.Called(amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(decimal.Decimal) error); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTrader interface {
	mock.TestingT
	Cleanup(func())
}

// NewTrader creates a new instance of Trader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTrader(t mockConstructorTestingTNewTrader) *Trader {
	mock := &Trader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
